-- PayDay Postgres baseline schema.
-- Compatible with Supabase SQL editor and Supabase CLI migrations.

CREATE TABLE IF NOT EXISTS interviews (
    id TEXT PRIMARY KEY,
    audio_url TEXT,
    filename TEXT NOT NULL,
    file_path TEXT NOT NULL,
    transcript TEXT,
    transcript_text TEXT,
    status TEXT NOT NULL,
    latest_stage TEXT NOT NULL DEFAULT 'upload',
    last_error TEXT,
    error_message TEXT,
    created_at TIMESTAMPTZ NOT NULL,
    analysis_schema_version INTEGER,
    persona_ruleset_version INTEGER,
    analysis_version TEXT,
    insights_json JSONB,
    CONSTRAINT interviews_status_check CHECK (status IN ('pending', 'processing', 'completed', 'failed'))
);

CREATE TABLE IF NOT EXISTS structured_responses (
    interview_id TEXT PRIMARY KEY REFERENCES interviews(id) ON DELETE CASCADE,
    smartphone_user BOOLEAN,
    has_bank_account BOOLEAN,
    per_household_earnings TEXT,
    participant_personal_monthly_income TEXT,
    total_household_monthly_income TEXT,
    income_range TEXT,
    borrowing_history TEXT,
    repayment_preference TEXT,
    loan_interest TEXT,
    segmented_dialogue JSONB,
    analysis_version TEXT,
    analyzed_at TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS insights (
    interview_id TEXT PRIMARY KEY REFERENCES interviews(id) ON DELETE CASCADE,
    summary TEXT NOT NULL,
    key_quotes JSONB NOT NULL,
    persona TEXT NOT NULL,
    confidence_score DOUBLE PRECISION NOT NULL,
    analysis_version TEXT,
    analyzed_at TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS jobs (
    id TEXT PRIMARY KEY,
    batch_id TEXT NOT NULL,
    interview_id TEXT NOT NULL REFERENCES interviews(id) ON DELETE CASCADE,
    filename TEXT NOT NULL,
    content_type TEXT NOT NULL,
    payload BYTEA NOT NULL,
    status TEXT NOT NULL,
    attempts INTEGER NOT NULL DEFAULT 0,
    max_attempts INTEGER NOT NULL DEFAULT 3,
    error_message TEXT,
    cancel_requested BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    started_at TIMESTAMPTZ,
    completed_at TIMESTAMPTZ,
    CONSTRAINT jobs_status_check CHECK (status IN ('pending', 'processing', 'completed', 'failed', 'cancelled'))
);

CREATE TABLE IF NOT EXISTS processing_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    file_id TEXT NOT NULL REFERENCES interviews(id) ON DELETE CASCADE,
    stage TEXT NOT NULL,
    status TEXT NOT NULL,
    message TEXT,
    created_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT processing_events_status_check CHECK (status IN ('pending', 'processing', 'completed', 'failed'))
);

CREATE INDEX IF NOT EXISTS idx_interviews_status_created_at
    ON interviews (status, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_jobs_status_created_at
    ON jobs (status, created_at ASC);

CREATE INDEX IF NOT EXISTS idx_jobs_batch_id
    ON jobs (batch_id);

CREATE INDEX IF NOT EXISTS idx_processing_events_file_created
    ON processing_events (file_id, created_at DESC, id DESC);
