-- Postgres compatibility migration for legacy/SQLite-shaped rows.
-- Safe to run repeatedly in Supabase SQL editor.

ALTER TABLE IF EXISTS interviews ADD COLUMN IF NOT EXISTS audio_url TEXT;
ALTER TABLE IF EXISTS interviews ADD COLUMN IF NOT EXISTS filename TEXT;
ALTER TABLE IF EXISTS interviews ADD COLUMN IF NOT EXISTS file_path TEXT;
ALTER TABLE IF EXISTS interviews ADD COLUMN IF NOT EXISTS transcript TEXT;
ALTER TABLE IF EXISTS interviews ADD COLUMN IF NOT EXISTS transcript_text TEXT;
ALTER TABLE IF EXISTS interviews ADD COLUMN IF NOT EXISTS latest_stage TEXT NOT NULL DEFAULT 'upload';
ALTER TABLE IF EXISTS interviews ADD COLUMN IF NOT EXISTS last_error TEXT;
ALTER TABLE IF EXISTS interviews ADD COLUMN IF NOT EXISTS error_message TEXT;
ALTER TABLE IF EXISTS interviews ADD COLUMN IF NOT EXISTS analysis_schema_version INTEGER;
ALTER TABLE IF EXISTS interviews ADD COLUMN IF NOT EXISTS persona_ruleset_version INTEGER;
ALTER TABLE IF EXISTS interviews ADD COLUMN IF NOT EXISTS analysis_version TEXT;
ALTER TABLE IF EXISTS interviews ADD COLUMN IF NOT EXISTS insights_json JSONB;

ALTER TABLE IF EXISTS structured_responses ADD COLUMN IF NOT EXISTS per_household_earnings TEXT;
ALTER TABLE IF EXISTS structured_responses ADD COLUMN IF NOT EXISTS participant_personal_monthly_income TEXT;
ALTER TABLE IF EXISTS structured_responses ADD COLUMN IF NOT EXISTS total_household_monthly_income TEXT;
ALTER TABLE IF EXISTS structured_responses ADD COLUMN IF NOT EXISTS segmented_dialogue JSONB;
ALTER TABLE IF EXISTS structured_responses ADD COLUMN IF NOT EXISTS analysis_version TEXT;
ALTER TABLE IF EXISTS structured_responses ADD COLUMN IF NOT EXISTS analyzed_at TIMESTAMPTZ;

ALTER TABLE IF EXISTS insights ADD COLUMN IF NOT EXISTS analysis_version TEXT;
ALTER TABLE IF EXISTS insights ADD COLUMN IF NOT EXISTS analyzed_at TIMESTAMPTZ;

ALTER TABLE IF EXISTS jobs ADD COLUMN IF NOT EXISTS attempts INTEGER NOT NULL DEFAULT 0;
ALTER TABLE IF EXISTS jobs ADD COLUMN IF NOT EXISTS max_attempts INTEGER NOT NULL DEFAULT 3;
ALTER TABLE IF EXISTS jobs ADD COLUMN IF NOT EXISTS cancel_requested BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE IF EXISTS jobs ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ;

UPDATE jobs
SET updated_at = COALESCE(updated_at, now())
WHERE updated_at IS NULL;

-- Normalize key interview columns from legacy values.
UPDATE interviews
SET file_path = COALESCE(NULLIF(BTRIM(file_path), ''), NULLIF(BTRIM(audio_url), ''), id)
WHERE file_path IS NULL OR BTRIM(file_path) = '';

UPDATE interviews
SET filename = COALESCE(NULLIF(BTRIM(filename), ''), file_path)
WHERE filename IS NULL OR BTRIM(filename) = '';

UPDATE interviews
SET transcript_text = COALESCE(transcript_text, transcript)
WHERE transcript_text IS NULL;

UPDATE interviews
SET error_message = COALESCE(error_message, last_error)
WHERE error_message IS NULL;

UPDATE interviews
SET status = CASE LOWER(BTRIM(status))
    WHEN 'uploaded' THEN 'pending'
    WHEN 'upload' THEN 'pending'
    WHEN 'in_progress' THEN 'processing'
    WHEN 'complete' THEN 'completed'
    WHEN 'error' THEN 'failed'
    WHEN 'pending' THEN 'pending'
    WHEN 'processing' THEN 'processing'
    WHEN 'completed' THEN 'completed'
    WHEN 'failed' THEN 'failed'
    ELSE 'pending'
END
WHERE status IS DISTINCT FROM CASE LOWER(BTRIM(status))
    WHEN 'uploaded' THEN 'pending'
    WHEN 'upload' THEN 'pending'
    WHEN 'in_progress' THEN 'processing'
    WHEN 'complete' THEN 'completed'
    WHEN 'error' THEN 'failed'
    WHEN 'pending' THEN 'pending'
    WHEN 'processing' THEN 'processing'
    WHEN 'completed' THEN 'completed'
    WHEN 'failed' THEN 'failed'
    ELSE 'pending'
END;

CREATE INDEX IF NOT EXISTS idx_interviews_status_created_at
    ON interviews (status, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_jobs_status_created_at
    ON jobs (status, created_at ASC);

CREATE INDEX IF NOT EXISTS idx_jobs_batch_id
    ON jobs (batch_id);

CREATE TABLE IF NOT EXISTS processing_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    file_id TEXT NOT NULL REFERENCES interviews(id) ON DELETE CASCADE,
    stage TEXT NOT NULL,
    status TEXT NOT NULL,
    message TEXT,
    created_at TIMESTAMPTZ NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_processing_events_file_created
    ON processing_events (file_id, created_at DESC, id DESC);
