"""Postgres query equivalents for SQLite-focused repository operations.

This module is intentionally query-only so migration/planning work can move
incrementally toward Supabase/Postgres without changing the active SQLite
runtime repository in one step.
"""

from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class PostgresAuditItem:
    sqlite_pattern: str
    postgres_equivalent: str
    notes: str


POSTGRES_SQL_AUDIT: tuple[PostgresAuditItem, ...] = (
    PostgresAuditItem(
        sqlite_pattern="PRAGMA foreign_keys = ON",
        postgres_equivalent="(none) FK enforcement is always on",
        notes="Postgres enforces foreign keys natively once constraints exist.",
    ),
    PostgresAuditItem(
        sqlite_pattern="PRAGMA table_info(<table>)",
        postgres_equivalent=(
            "SELECT column_name FROM information_schema.columns "
            "WHERE table_schema = 'public' AND table_name = $1"
        ),
        notes="Use information_schema for schema introspection.",
    ),
    PostgresAuditItem(
        sqlite_pattern="SELECT name FROM sqlite_master WHERE type='table' ...",
        postgres_equivalent="SELECT to_regclass('public.jobs') IS NOT NULL AS table_exists",
        notes="to_regclass returns NULL when a relation does not exist.",
    ),
    PostgresAuditItem(
        sqlite_pattern="INTEGER PRIMARY KEY AUTOINCREMENT",
        postgres_equivalent="BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
        notes="Identity columns replace SQLite autoincrement behavior.",
    ),
    PostgresAuditItem(
        sqlite_pattern="? parameter placeholders",
        postgres_equivalent="$1, $2, ... placeholders",
        notes="psycopg-style positional bind variables.",
    ),
    PostgresAuditItem(
        sqlite_pattern="WHERE id IN (?, ?, ...)",
        postgres_equivalent="WHERE id = ANY($1::text[])",
        notes="Avoids dynamic placeholder expansion for variable IN lists.",
    ),
    PostgresAuditItem(
        sqlite_pattern="INTEGER booleans (0/1)",
        postgres_equivalent="BOOLEAN true/false",
        notes="Use true booleans for smartphone_user/has_bank_account/cancel_requested.",
    ),
)


POSTGRES_REPOSITORY_QUERIES: dict[str, str] = {
    "insert_or_update_structured_response": """
        INSERT INTO structured_responses (
            interview_id,
            smartphone_user,
            has_bank_account,
            per_household_earnings,
            participant_personal_monthly_income,
            total_household_monthly_income,
            income_range,
            borrowing_history,
            repayment_preference,
            loan_interest,
            segmented_dialogue,
            analysis_version,
            analyzed_at
        )
        VALUES (
            $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11::jsonb, $12, $13::timestamptz
        )
        ON CONFLICT(interview_id) DO UPDATE SET
            smartphone_user = EXCLUDED.smartphone_user,
            has_bank_account = EXCLUDED.has_bank_account,
            per_household_earnings = EXCLUDED.per_household_earnings,
            participant_personal_monthly_income = EXCLUDED.participant_personal_monthly_income,
            total_household_monthly_income = EXCLUDED.total_household_monthly_income,
            income_range = EXCLUDED.income_range,
            borrowing_history = EXCLUDED.borrowing_history,
            repayment_preference = EXCLUDED.repayment_preference,
            loan_interest = EXCLUDED.loan_interest,
            segmented_dialogue = EXCLUDED.segmented_dialogue,
            analysis_version = EXCLUDED.analysis_version,
            analyzed_at = EXCLUDED.analyzed_at
    """,
    "insert_or_update_insight": """
        INSERT INTO insights (
            interview_id, summary, key_quotes, persona, confidence_score, analysis_version, analyzed_at
        )
        VALUES ($1, $2, $3::jsonb, $4, $5::double precision, $6, $7::timestamptz)
        ON CONFLICT(interview_id) DO UPDATE SET
            summary = EXCLUDED.summary,
            key_quotes = EXCLUDED.key_quotes,
            persona = EXCLUDED.persona,
            confidence_score = EXCLUDED.confidence_score,
            analysis_version = EXCLUDED.analysis_version,
            analyzed_at = EXCLUDED.analyzed_at
    """,
    "list_interviews": """
        SELECT
            interviews.id,
            COALESCE(interviews.filename, '') AS filename,
            COALESCE(interviews.file_path, interviews.audio_url) AS file_path,
            interviews.status,
            interviews.created_at,
            insights.persona,
            insights.confidence_score,
            insights.summary
        FROM interviews
        LEFT JOIN insights ON insights.interview_id = interviews.id
        WHERE ($1::text IS NULL OR interviews.status = $1)
        ORDER BY interviews.created_at DESC, interviews.id DESC
        LIMIT $2
    """,
    "list_stale_interview_ids": """
        SELECT interviews.id
        FROM interviews
        LEFT JOIN insights ON insights.interview_id = interviews.id
        LEFT JOIN structured_responses ON structured_responses.interview_id = interviews.id
        WHERE COALESCE(interviews.transcript_text, interviews.transcript) IS NOT NULL
          AND BTRIM(COALESCE(interviews.transcript_text, interviews.transcript)) <> ''
          AND (
                interviews.analysis_schema_version IS NULL
                OR interviews.analysis_schema_version < $1
                OR interviews.persona_ruleset_version IS NULL
                OR interviews.persona_ruleset_version < $2
                OR insights.persona IS NULL
                OR structured_responses.interview_id IS NULL
                OR structured_responses.analysis_version IS NULL
                OR insights.analysis_version IS NULL
                OR structured_responses.analysis_version <> insights.analysis_version
                OR ($3::text IS NOT NULL AND (interviews.analysis_version IS NULL OR interviews.analysis_version <> $3))
          )
        ORDER BY interviews.created_at DESC, interviews.id DESC
        LIMIT $4
    """,
    "list_stale_corrupted_interviews_subset": """
        SELECT id, status, COALESCE(error_message, last_error) AS last_error,
               COALESCE(transcript_text, transcript) AS transcript
        FROM interviews
        WHERE id = ANY($1::text[])
        ORDER BY created_at DESC, id DESC
    """,
    "claim_job": """
        UPDATE jobs
        SET status = 'processing',
            attempts = attempts + 1,
            updated_at = $2::timestamptz,
            started_at = COALESCE(started_at, $2::timestamptz),
            error_message = NULL
        WHERE id = $1
          AND status = 'pending'
          AND cancel_requested = FALSE
        RETURNING id
    """,
}
